# Generated by Django 5.1.5 on 2025-02-09 14:00

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='Имя')),
                ('last_name', models.CharField(blank=True, default='яя', max_length=100, null=True, verbose_name='Фамилия')),
                ('metro', models.CharField(blank=True, default='яя', max_length=255, null=True, verbose_name='Метро')),
                ('street', models.CharField(blank=True, default='яя', max_length=255, null=True, verbose_name='Улица')),
                ('house_number', models.CharField(blank=True, default='яя', max_length=10, null=True, verbose_name='Номер дома')),
                ('entrance', models.CharField(blank=True, default='яя', max_length=10, null=True, verbose_name='Подъезд')),
                ('floor', models.CharField(blank=True, default='яя', max_length=10, null=True, verbose_name='Этаж')),
                ('flat_number', models.CharField(blank=True, default='яя', max_length=10, null=True, verbose_name='Номер квартиры')),
                ('intercom', models.CharField(blank=True, default='яя', max_length=50, null=True, verbose_name='Домофон')),
                ('phone', models.CharField(blank=True, default='яя', max_length=20, null=True, verbose_name='Телефон')),
                ('price_offline', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, verbose_name='Цена за работу оффлайн')),
                ('price_online', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, verbose_name='Цена за работу онлайн')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clients', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Block',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('block_number', models.PositiveIntegerField(verbose_name='Номер блока')),
                ('total_meetings', models.PositiveIntegerField(verbose_name='Количество встреч в блоке')),
                ('completed_meetings', models.PositiveIntegerField(default=0, verbose_name='Пройденные встречи')),
                ('cost', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Стоимость блока')),
                ('status', models.CharField(choices=[('active', 'Активный'), ('completed', 'Завершённый')], default='active', max_length=10, verbose_name='Статус блока')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocks', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocks', to='MyClient.client', verbose_name='Клиент')),
            ],
            options={
                'verbose_name': 'Блок встреч',
                'verbose_name_plural': 'Блоки встреч',
                'ordering': ['client', 'block_number'],
                'unique_together': {('client', 'block_number')},
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Имя')),
                ('surname', models.CharField(max_length=100, verbose_name='Фамилия')),
                ('specialization', models.CharField(blank=True, max_length=255, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='Дата')),
                ('time', models.TimeField(verbose_name='Время')),
                ('is_online', models.BooleanField(default=False, verbose_name='Онлайн')),
                ('is_completed', models.BooleanField(default=False, verbose_name='Выполнено')),
                ('is_paid', models.BooleanField(default=False, verbose_name='Оплачено')),
                ('is_canceled', models.BooleanField(default=False, verbose_name='Отменено')),
                ('cost', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Стоимость')),
                ('block', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='MyClient.block', verbose_name='Привязанный блок')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='MyClient.client')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
        ),
    ]
