# Generated by Django 5.1.5 on 2025-01-21 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyClient', '0006_client_created_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='client',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterField(
            model_name='client',
            name='entrance',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Подъезд'),
        ),
        migrations.AlterField(
            model_name='client',
            name='floor',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Этаж'),
        ),
        migrations.AlterField(
            model_name='client',
            name='house_number',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Номер дома'),
        ),
        migrations.AlterField(
            model_name='client',
            name='last_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Фамилия'),
        ),
        migrations.AlterField(
            model_name='client',
            name='metro',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Метро'),
        ),
        migrations.AlterField(
            model_name='client',
            name='price_offline',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, verbose_name='Цена за работу оффлайн'),
        ),
        migrations.AlterField(
            model_name='client',
            name='price_online',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, verbose_name='Цена за работу онлайн'),
        ),
        migrations.AlterField(
            model_name='client',
            name='street',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Улица'),
        ),
    ]
