# Generated by Django 5.1.5 on 2025-01-21 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyClient', '0007_alter_client_options_alter_client_entrance_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Телефон'),
        ),
    ]
