# Generated by Django 5.1.5 on 2025-01-24 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyClient', '0009_alter_client_entrance_alter_client_floor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='is_paid',
            field=models.BooleanField(default=False, verbose_name='Оплачено'),
        ),
        migrations.AlterField(
            model_name='client',
            name='entrance',
            field=models.CharField(blank=True, default='яя', max_length=10, null=True, verbose_name='Подъезд'),
        ),
        migrations.AlterField(
            model_name='client',
            name='floor',
            field=models.CharField(blank=True, default='яя', max_length=10, null=True, verbose_name='Этаж'),
        ),
        migrations.AlterField(
            model_name='client',
            name='house_number',
            field=models.CharField(blank=True, default='яя', max_length=10, null=True, verbose_name='Номер дома'),
        ),
        migrations.AlterField(
            model_name='client',
            name='intercom',
            field=models.CharField(blank=True, default='яя', max_length=50, null=True, verbose_name='Домофон'),
        ),
        migrations.AlterField(
            model_name='client',
            name='last_name',
            field=models.CharField(blank=True, default='яя', max_length=100, null=True, verbose_name='Фамилия'),
        ),
        migrations.AlterField(
            model_name='client',
            name='metro',
            field=models.CharField(blank=True, default='яя', max_length=255, null=True, verbose_name='Метро'),
        ),
        migrations.AlterField(
            model_name='client',
            name='phone',
            field=models.CharField(blank=True, default='яя', max_length=20, null=True, verbose_name='Телефон'),
        ),
        migrations.AlterField(
            model_name='client',
            name='street',
            field=models.CharField(blank=True, default='яя', max_length=255, null=True, verbose_name='Улица'),
        ),
    ]
