# Generated by Django 5.1.5 on 2025-02-02 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyClient', '0010_schedule_is_paid_alter_client_entrance_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='is_canceled',
            field=models.BooleanField(default=False, verbose_name='Отменено'),
        ),
    ]
