# Generated by Django 5.1.5 on 2025-02-03 19:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyClient', '0011_schedule_is_canceled'),
    ]

    operations = [
        migrations.CreateModel(
            name='Block',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('block_number', models.PositiveIntegerField(verbose_name='Номер блока')),
                ('total_meetings', models.PositiveIntegerField(verbose_name='Количество встреч в блоке')),
                ('completed_meetings', models.PositiveIntegerField(default=0, verbose_name='Пройденные встречи')),
                ('cost', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Стоимость блока')),
                ('status', models.CharField(choices=[('active', 'Активный'), ('completed', 'Завершённый')], default='active', max_length=10, verbose_name='Статус блока')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocks', to='MyClient.client', verbose_name='Клиент')),
            ],
            options={
                'verbose_name': 'Блок встреч',
                'verbose_name_plural': 'Блоки встреч',
                'ordering': ['client', 'block_number'],
                'unique_together': {('client', 'block_number')},
            },
        ),
    ]
