# Generated by Django 5.1.5 on 2025-02-07 21:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyClient', '0012_block'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='block',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='MyClient.block', verbose_name='Привязанный блок'),
        ),
    ]
